# Use a base image with Python
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script into the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the script every 10 seconds
CMD ["sh", "-c", "while true; do python FlirOneSensorSim.py; sleep 10; done"]