# Use a base image with Python
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script into the container
COPY FlirOneSensorSim.py .

# Install any required packages

# Run the script every 10 seconds
CMD ["python", "FlirOneSensorInterface.py"]