version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=flironesensor
      - INFLUXDB_ADMIN_USER=senne
      - INFLUXDB_ADMIN_PASSWORD=12345678
    volumes:
      - influxdb-storage:/var/lib/influxdb

  flir_sensor_sim:
    build:
      context: .
      dockerfile: dockerfile.sim
    container_name: flir_sensor_sim
    depends_on:
      - influxdb
    volumes:
      - ./flir_sensor_sim_data:/app/data

  flir_sensor:
    build:
      context: .
      dockerfile: dockerfile
    container_name: flir_sensor
    depends_on:
      - influxdb
    environment:
      - PATIENT_ID=123
    volumes:
      - ./SensorOutput:/SensorOutput

volumes:
  influxdb-storage:
